version: '3'
services:
  app-server:
    image: takuyafujimoto/tms-tomcat8-java8
    command: >
      ./bin/catalina.sh run
    volumes:
      - ./app-server/webapps/:/usr/local/tomcat/webapps
    ports:
      - "80:8080"